# Name of the workflow as it will appear in the GitHub Actions tab
name: CI

# Events that trigger the workflow
on:
  push:  # Trigger when code is pushed
    branches: [main]  # Only on the 'main' branch
  pull_request:  # Trigger on pull requests
    branches: [main]  # Only when the base branch of the PR is 'main'

# A job represents a collection of steps that are executed sequentially on the same runner
jobs:
  build:  # Name of the job
    runs-on: ubuntu-latest  # The type of virtual host to run the job on

    # Steps are a series of tasks that are executed sequentially in a job
    steps:
    - name: Checkout repository  # Name of the step
      uses: actions/checkout@v2  # Action to check out the repository code

    - name: Set up Node.js  # Name of the step
      uses: actions/setup-node@v2  # Action to set up a Node.js environment
      with:
        node-version: '20'  # Specify the version of Node.js to use

    - name: Install dependencies  # Name of the step
      run: npm install  # Command to install Node.js dependencies

    - name: Run tests  # Name of the step
      run: npm test  # Command to run tests, assumes a test script exists in package.json

    - name: Lint  # Name of the step
      run: npm run lint  # Command to run the linting process, assumes a lint script exists in package.json
